#!/usr/bin/env bash
# Script to restore all backed up assets to original locations
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
cd "$REPO_DIR"

cp -v "_assets_backup/raw_user_uploads/Triphala & Guduchi Side-by-Side.png" "Triphala & Guduchi Side-by-Side.png"
cp -v "_assets_backup/raw_user_uploads/k01.png" "k01.png"
cp -v "_assets_backup/raw_user_uploads/k02.png" "k02.png"
cp -v "_assets_backup/raw_user_uploads/k03.png" "k03.png"
cp -v "_assets_backup/raw_user_uploads/k04.png" "k04.png"
cp -v "_assets_backup/raw_user_uploads/k04_raw.png" "k04_raw.png"
cp -v "_assets_backup/old_medicine_jars/jar_k01.jpg" "assets/jar_k01.jpg"
cp -v "_assets_backup/old_medicine_jars/jar_k02.jpg" "assets/jar_k02.jpg"
cp -v "_assets_backup/old_medicine_jars/jar_k03.jpg" "assets/jar_k03.jpg"
cp -v "_assets_backup/old_medicine_jars/jar_k04.jpg" "assets/jar_k04.jpg"
cp -v "_assets_backup/old_medicine_jars/jar_triphala.jpg" "assets/jar_triphala.jpg"
cp -v "_assets_backup/old_medicine_jars/bundle_duo.jpg" "assets/bundle_duo.jpg"
cp -v "_assets_backup/unused_graphics_and_crops/botanical_card_crop.png" "assets/botanical_card_crop.png"
cp -v "_assets_backup/unused_graphics_and_crops/botanical_profile.png" "assets/botanical_profile.png"
cp -v "_assets_backup/unused_graphics_and_crops/botanical_profile.svg" "assets/botanical_profile.svg"
cp -v "_assets_backup/unused_graphics_and_crops/botanical_profile_transparent.png" "assets/botanical_profile_transparent.png"
cp -v "_assets_backup/unused_graphics_and_crops/bundle_duo_pods.svg" "assets/bundle_duo_pods.svg"
cp -v "_assets_backup/unused_graphics_and_crops/duo_pods_real.png" "assets/duo_pods_real.png"
cp -v "_assets_backup/unused_graphics_and_crops/hero_seed_jars.jpg" "assets/hero_seed_jars.jpg"
cp -v "_assets_backup/unused_graphics_and_crops/ikwath_appliance.jpg" "assets/ikwath_appliance.jpg"
cp -v "_assets_backup/unused_graphics_and_crops/logo_transparent.png" "assets/logo_transparent.png"
cp -v "_assets_backup/unused_graphics_and_crops/logo_white.png" "assets/logo_white.png"
cp -v "_assets_backup/unused_graphics_and_crops/pod_k01.svg" "assets/pod_k01.svg"
cp -v "_assets_backup/unused_graphics_and_crops/pod_k02.svg" "assets/pod_k02.svg"
cp -v "_assets_backup/unused_graphics_and_crops/pod_k03.svg" "assets/pod_k03.svg"
cp -v "_assets_backup/unused_graphics_and_crops/pod_k04.svg" "assets/pod_k04.svg"
cp -v "_assets_backup/unused_graphics_and_crops/pods_reference.jpg" "assets/pods_reference.jpg"
cp -v "_assets_backup/unused_graphics_and_crops/science_user_macro.png" "assets/science_user_macro.png"
cp -v "_assets_backup/unused_graphics_and_crops/warm_cup.jpg" "assets/warm_cup.jpg"
cp -v "_assets_backup/unused_graphics_and_crops/app_preview_frame1.jpg" "assets/app_preview_frame1.jpg"
cp -v "_assets_backup/unused_graphics_and_crops/herb.mp4" "assets/herb.mp4"
